name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: |
          cd api
          dotnet restore

      - name: Build solution
        run: |
          cd api
          dotnet build --no-restore --configuration Release

      - name: Run tests
        run: |
          cd api
          dotnet test --no-build --configuration Release --verbosity normal
